# -*- coding: utf-8 -*-
"""Copy of Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14_Zvq9IYAhF63e8sa2i3-10IUQ8Cj52p
"""

# ==============================
# Install required libraries
# ==============================
!pip install pandas openpyxl folium geopy

# ==============================
# Import libraries
# ==============================
import pandas as pd
import folium
from geopy.geocoders import Nominatim
import time
import os

# ==============================
# Load Excel files
# (update the file paths if needed)
# ==============================
# Use forward slashes for file paths in Colab
file_path_projects = "/content/Green_H2_project_india_sites.xlsx"
file_path_potential = "/content/green_hydrogen_potential_india_sites.xlsx"

if not os.path.exists(file_path_projects):
    print(f"Error: File not found at {file_path_projects}")
    df_projects = None # Explicitly set to None if not found
else:
    df_projects = pd.read_excel(file_path_projects)  # Red markers

if not os.path.exists(file_path_potential):
    print(f"Error: File not found at {file_path_potential}")
    df_potential = None # Explicitly set to None if not found
else:
    df_potential = pd.read_excel(file_path_potential)  # Blue markers


# ==============================
# Geocoding for project sites (first file)
# ==============================
geolocator = Nominatim(user_agent="geoapi")

def get_lat_lon(location):
    try:
        # add India for better accuracy, ensure location is a string
        loc = geolocator.geocode(str(location) + ", India")
        time.sleep(1)  # avoid hitting API limit
        if loc:
            return pd.Series([loc.latitude, loc.longitude])
        else:
            return pd.Series([None, None])
    except Exception as e:
        print(f"Error geocoding {location}: {e}")
        return pd.Series([None, None])

# Check if df_projects exists before applying geocoding
# Assuming "State" or "Region" column in the first file (check column name)
# Replace 'Location' below with the correct column name from your sheet
if df_projects is not None and 'Location' in df_projects.columns:
  df_projects[['Latitude', 'Longitude']] = df_projects['Location'].apply(get_lat_lon)
elif df_projects is not None:
    print("Error: 'Location' column not found in df_projects. Please check column name.")


# ==============================
# Potential sites already have Lat/Lon (check column names!)
# ==============================
# Check if df_potential exists before renaming columns
if df_potential is not None:
  # Replace 'Latitude' and 'Longitude' below if your columns have different names
  # Also check if 'lat' and 'lon' columns exist before renaming
  if 'lat' in df_potential.columns and 'lon' in df_potential.columns:
    df_potential = df_potential.rename(columns={"lat": "Latitude", "lon": "Longitude"})  # <-- update if needed
  else:
    print("Error: 'lat' or 'lon' columns not found in df_potential. Please check column names.")

# ==============================
# Create Map
# ==============================
india_map = folium.Map(location=[22.9734, 78.6569], zoom_start=5)  # India center

# Add project sites (red markers)
if df_projects is not None and 'Latitude' in df_projects.columns and 'Longitude' in df_projects.columns:
  for idx, row in df_projects.dropna(subset=['Latitude','Longitude']).iterrows():
      folium.Marker(
          location=[row['Latitude'], row['Longitude']],
          # Ensure 'Location' column exists before accessing
          popup=f"Project Site: {row.get('Location', 'N/A')}",
          icon=folium.Icon(color="red")
      ).add_to(india_map)
elif df_projects is not None:
    print("Error: 'Latitude' or 'Longitude' columns not found in df_projects after geocoding.")


# Add potential sites (blue markers)
if df_potential is not None and 'Latitude' in df_potential.columns and 'Longitude' in df_potential.columns:
  for idx, row in df_potential.dropna(subset=['Latitude','Longitude']).iterrows():
      folium.Marker(
          location=[row['Latitude'], row['Longitude']],
          popup=f"Potential Site",
          icon=folium.Icon(color="blue")
      ).add_to(india_map)
elif df_potential is not None:
    print("Error: 'Latitude' or 'Longitude' columns not found in df_potential.")


# Save & Display Map
india_map.save("india_green_h2_map.html")
india_map

print("Projects (first 5 rows):")
if df_projects is not None:
    print(df_projects.head())
else:
    print("df_projects was not loaded.")

print("\nPotential sites (first 5 rows):")
if df_potential is not None:
    print(df_potential.head())
else:
    print("df_potential was not loaded.")

import folium

# Center over India
test_map = folium.Map(location=[22.97, 78.65], zoom_start=5)

# Add one red marker
folium.Marker(
    location=[28.61, 77.23],  # Delhi
    popup="Test Red",
    icon=folium.Icon(color="red")
).add_to(test_map)

# Center over India
test_map = folium.Map(location=[24.183,78.203], zoom_start=5)

# Add one red marker
folium.Marker(
    location=[24.183,78.203],  # MP-Bina
    popup="Test Red",
    icon=folium.Icon(color="red")
).add_to(test_map)

# Add one red marker
folium.Marker(
    location=[17.686,83.218],  # Vishakhapatnam
    popup="Test Red",
    icon=folium.Icon(color="red")
).add_to(test_map)

# Add one red marker
folium.Marker(
    location=[22.258,71.192],  #Gujarat
    popup="Test Red",
    icon=folium.Icon(color="red")
).add_to(test_map)

# Add one red marker
folium.Marker(
    location=[26.757,94.203],  #Assam-Jorhat
    popup="Test Red",
    icon=folium.Icon(color="red")
).add_to(test_map)

# Add one red marker
folium.Marker(
    location=[21.170,72.831],  #Gujarat-Surat
    popup="Test Red",
    icon=folium.Icon(color="red")
).add_to(test_map)

# Add one red marker
folium.Marker(
    location=[23.259,77.412],  #MP
    popup="Test Red",
    icon=folium.Icon(color="red")
).add_to(test_map)

# Add one red marker
folium.Marker(
    location=[24.100,82.650],  #MP-Vindhyachal
    popup="Test Red",
    icon=folium.Icon(color="red")
).add_to(test_map)

# Add one red marker
folium.Marker(
    location=[28.022,73.311],  #Rajasthan-Bikaner
    popup="Test Red",
    icon=folium.Icon(color="red")
).add_to(test_map)

# Add one red marker
folium.Marker(
    location=[34.152,77.577],  #Ladakh-Leh
    popup="Test Red",
    icon=folium.Icon(color="red")
).add_to(test_map)

# Add one red marker
folium.Marker(
    location=[23.176,75.788],  #MP-Ujjain(Makone)
    popup="Test Red",
    icon=folium.Icon(color="red")
).add_to(test_map)

# Add one red marker
folium.Marker(
    location=[18.800,79.450],  #Telengana-Ramagundam
    popup="Test Red",
    icon=folium.Icon(color="red")
).add_to(test_map)

# Add one red marker
folium.Marker(
    location=[29.390,76.963],  #Haryana-Panipat
    popup="Test Red",
    icon=folium.Icon(color="red")
).add_to(test_map)

# Add one red marker
folium.Marker(
    location=[27.492,77.673],  #UP-Mathura
    popup="Test Red",
    icon=folium.Icon(color="red")
).add_to(test_map)

# Add one red marker
folium.Marker(
    location=[21.046,75.787],  #Maharastra-Busawal
    popup="Test Red",
    icon=folium.Icon(color="red")
).add_to(test_map)

# Add one red marker
folium.Marker(
    location=[12.971,77.594],  #Karnataka-Banglore
    popup="Test Red",
    icon=folium.Icon(color="red")
).add_to(test_map)

# Add one red marker
folium.Marker(
    location=[11.750,79.750],  #TamilNadu-Cuddalore
    popup="Test Red",
    icon=folium.Icon(color="red")
).add_to(test_map)

# Add one red marker
folium.Marker(
    location=[22.258,71.192],  #Gujarat-Adani Project
    popup="Test Red",
    icon=folium.Icon(color="red")
).add_to(test_map)


test_map

import folium

# Center over India
test_map = folium.Map(location=[22.97, 78.65], zoom_start=5)

# Add one blue marker
folium.Marker(
    location=[24.200,82.650],  # Singrauli-MP
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[21.764,72.151],  # Bhavnagar
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[27.472,94.912],  # Dibrugarah
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[21.717,72.617],  # Dahej-Guj
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[24.536,81.303],  # Rewa
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[26.911,70.922],  # Jaisalmer,RAJ
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[34.568,76.110],  # Kargil
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[22.719,75.857],  # Indore
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[17.978,79.594],  # Warangel
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[28.408,77.317],  # Faridabad
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[26.449,80.331],  # Nagpur
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[19.07, 72.87],  # Mumbai
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[12.295,76.639],  # Mysuru
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[8.764,78.134],  # Tuticorin
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[23.033,70.217],  # Kandla
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[20.316,86.611],  # paradip
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[19.07, 72.87],  # Mumbai
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[23.733,69.859],  # Kutch
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

test_map

import folium
import folium

# Center over India
test_map = folium.Map(location=[22.97, 78.65], zoom_start=5)

# Add one blue marker
folium.Marker(
    location=[24.200,82.650],  # Singrauli-MP
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[21.764,72.151],  # Bhavnagar
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[27.472,94.912],  # Dibrugarah
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[21.717,72.617],  # Dahej-Guj
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[24.536,81.303],  # Rewa
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[26.911,70.922],  # Jaisalmer,RAJ
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[34.568,76.110],  # Kargil
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[22.719,75.857],  # Indore
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[17.978,79.594],  # Warangel
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[28.408,77.317],  # Faridabad
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[26.449,80.331],  # Nagpur
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[19.07, 72.87],  # Mumbai
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[12.295,76.639],  # Mysuru
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[8.764,78.134],  # Tuticorin
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[23.033,70.217],  # Kandla
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[20.316,86.611],  # paradip
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[19.07, 72.87],  # Mumbai
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add one blue marker
folium.Marker(
    location=[23.733,69.859],  # Kutch
    popup="Test Blue",
    icon=folium.Icon(color="green")
).add_to(test_map)

test_map
import folium

# Create base map
soil_map = folium.Map(location=[22.5, 78.9], zoom_start=5)

# Example 1: Marking Black Soil in Madhya Pradesh (Polygon)
black_soil_coords = [
    [23.5, 77.5],
    [23.5, 78.5],
    [24.0, 78.5],
    [24.0, 77.5]
]

folium.Polygon(
    locations=black_soil_coords,
    color="black",      # border color
    weight=2,
    fill=True,
    fill_color="black",
    fill_opacity=0.4,
    popup="Black Soil (Preferable for Green H2)"
).add_to(soil_map)

# Example 2: Alluvial Soil near UP (Circle)
folium.Circle(
    location=[26.8, 80.9],   # Kanpur
    radius=50000,           # in meters
    color="brown",
    fill=True,
    fill_color="brown",
    fill_opacity=0.4,
    popup="Alluvial Soil (Good)"
).add_to(soil_map)

# Example 3: Sandy Soil in Rajasthan
folium.CircleMarker(
    location=[27.0, 72.5],   # Jaisalmer
    radius=30,
    color="orange",
    fill=True,
    fill_color="orange",
    fill_opacity=0.5,
    popup="Sandy Soil (Less preferred)"
).add_to(soil_map)

soil_map